#PROGRAMMING EXERCISE 5-1
#ASSUME A FILE CONTAINING A SERIES OF INTEGERS IS NAMED NUMBERS.TXT AND EXISTS ON THE 
#COMPUTER'S DISK. WRITE A PROGRAM THAT DISPLAYSALL THE NUMBERS IN THE FILE

#
file = open ("numbers.txt", 'r')
numbers = file.read()
print (numbers)

file.close ()

